# @package _global_
module:
  _target_: emg2qwerty.lightning.TransformerCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  d_model: 128
  nhead: 4
  num_encoder_layers: 2
  dim_feedforward: 512
  dropout: 0.0
  use_cross_wrist_attention: false # Enable/disable attention between left and right wrists
  use_cross_sensor_attention: false # Enable/disable attention between the 16 EMG channels on each hand
  loss_type: 'ctc' # or 'cross_entropy'

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
